### PR TITLE
fix: inject default labels to support custom code block icons at correct timing

### LINKED ISSUE #578: custom items for code block
### Describe the bug

As per #577, this problem still persists

### Reproduction

Simply build the project with `theme-yun` and use some custom icons somewhere

### System Info

```Shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by JasonXuDeveloper**
fix: inject default labels to support custom code block icons at correct timing, close #578

### Description

Cannot inject the correct default labels to the custom icon plugin, which leads to lost custom code block icons

### Linked Issues
#578 and #573

### CODE REVIEW

File: packages/valaxy/node/plugins/preset.ts [hunk 1]
```diff
@@ -155,29 +155,107 @@ export async function ViteValaxyPlugins(
...
-        ...Object.keys(valaxyConfig.groupIcons?.customIcon || {}),
-        ...Array.from(codeBlockTitles),
-      ],
-    }),
-  )
+  let cachedGroupIconsCSS: string | null = null
+
+  // Create a custom plugin that intercepts the virtual CSS generation
+  const dynamicGroupIconPlugin: PluginOption = {
+    name: 'vitepress-plugin-group-icons',
```
Comment (YunYouJun) [inline packages/valaxy/node/plugins/preset.ts]: This seems to incorporate some of the logic of the group-icons.
Do we really need this?
If necessary, we should not use the same plugin names at this point.

Comment (JasonXuDeveloper) [reply packages/valaxy/node/plugins/preset.ts]: It is essential to have this, or we can't add code block titles to `defaultLabels` correctly, causing `data-label` not to be able to display custom icons.

I will change the name now

**Review by YunYouJun — APPROVED** [review]
